"use client";
import {useEffect,useState} from "react";import type {Content} from "../../lib/data";
type Item={id:number;title:string;category:string;description:string;fileName:string;mediaType:string;placement:string};
type ExtraProject={id:string;title:string;kicker:string;text:string;tags:string;meta:string};type ExtraExperience={id:string;date:string;org:string;role:string;work:string};
const placementNames:Record<string,string>={reel:"首页 Showreel",spring:"《春秋异闻录》",xiaomi:"小米汽车座舱演示",tools:"音频流程工具",archive:"更多声音作品"};
const groups=[
 ["基本信息",[["name","中文姓名"],["nameEn","英文姓名"],["role","职业定位"],["availability","可工作状态"],["email","联系邮箱"],["phone","联系电话"],["portfolioLabel","作品集链接文字"],["portfolioUrl","作品集网址"],["footerText","页脚职业文字"]]],
 ["导航",[["navWork","作品"],["navReel","Showreel"],["navAbout","关于"],["navContact","联系"]]],
 ["首页首屏",[["heroTitleBefore","主标题第一行"],["heroTitleAccent","主标题强调文字"],["heroTitleAfter","主标题结尾"],["headline","个人定位简介",true],["heroPrimary","主按钮"],["heroSecondary","Showreel 按钮"],["reelTitle","Showreel 标题"],["reelEmpty","未上传视频提示"],["reelLabel","Showreel 标签"]]],
 ["作品区",[["workKicker","英文小标题"],["workTitle","中文标题"],["workIntro","区域简介",true],["projectMeta","项目元信息"],["projectName","项目名称"],["projectRole","项目职责"],["projectIntro","项目简介",true],["projectFact1Label","数据 1 名称"],["projectFact1Value","数据 1 内容"],["projectFact2Label","数据 2 名称"],["projectFact2Value","数据 2 内容"],["projectFact3Label","数据 3 名称"],["projectFact3Value","数据 3 内容"],["projectBullets","项目工作内容（每行一项）",true],["projectTags","项目标签（逗号分隔）"]]],
 ["其他作品",[["spatialKicker","空间音频英文标题"],["spatialTitle","空间音频项目名"],["spatialText","空间音频介绍",true],["spatialTags","空间音频标签"],["toolsKicker","工具英文标题"],["toolsTitle","工具项目名"],["toolsText","工具介绍",true],["toolsTags","工具标签"],["toolsVisual","工具卡片大字"],["toolsCredit","工具卡片署名"],["mediaKicker","作品库英文标题"],["mediaTitle","作品库中文标题"]]],
 ["工作经历",[["experienceKicker","英文标题"],["experienceTitle","中文标题"],["exp1Date","经历 1 日期"],["exp1Org","经历 1 单位"],["exp1Role","经历 1 职位"],["exp1Work","经历 1 项目"],["exp2Date","经历 2 日期"],["exp2Org","经历 2 单位"],["exp2Role","经历 2 职位"],["exp2Work","经历 2 项目"],["exp3Date","经历 3 日期"],["exp3Org","经历 3 单位"],["exp3Role","经历 3 职位"],["exp3Work","经历 3 项目"]]],
 ["关于与教育",[["aboutKicker","英文标题"],["aboutTitle","中文标题"],["about","个人介绍",true],["location","所在地"],["edu1Date","教育 1 日期"],["edu1School","教育 1 学校"],["edu1Text","教育 1 专业"],["edu2Date","教育 2 日期"],["edu2School","教育 2 学校"],["edu2Text","教育 2 专业"],["skills","技能（逗号分隔）",true]]],
 ["联系区",[["contactKicker","英文标题"],["contactTitleBefore","标题第一行"],["contactTitleAccent","强调文字"],["contactTitleAfter","标题结尾"],["contactIntro","联系说明",true]]],
] as const;

type UploadProgress={percent:number;loaded:number;total:number;speed:number};
const formatBytes=(bytes:number)=>bytes>=1024*1024?`${(bytes/1024/1024).toFixed(1)} MB`:`${(bytes/1024).toFixed(0)} KB`;
function uploadWithProgress(url:string,file:File,token:string,onProgress:(progress:UploadProgress)=>void){return new Promise<{path:string}>((resolve,reject)=>{const xhr=new XMLHttpRequest();const started=Date.now();let lastProgress=Date.now();const stalled=window.setInterval(()=>{if(Date.now()-lastProgress>90_000){xhr.abort();reject(new Error("连续 90 秒没有上传进度。请检查网络，或换用更稳定的网络后重试。"))}},5_000);const finish=()=>window.clearInterval(stalled);xhr.open("POST",url);xhr.timeout=30*60_000;xhr.setRequestHeader("Authorization",`Bearer ${token}`);xhr.setRequestHeader("Content-Type",file.type||"application/octet-stream");xhr.upload.onprogress=e=>{lastProgress=Date.now();const loaded=e.loaded;const total=e.lengthComputable?e.total:file.size;onProgress({percent:Math.min(100,Math.round(loaded/total*100)),loaded,total,speed:loaded/Math.max(1,(Date.now()-started)/1000)})};xhr.onload=()=>{finish();if(xhr.status>=200&&xhr.status<300){try{const result=JSON.parse(xhr.responseText) as {path:string};onProgress({percent:100,loaded:file.size,total:file.size,speed:file.size/Math.max(1,(Date.now()-started)/1000)});resolve(result)}catch{reject(new Error("服务器没有返回有效的文件地址。"))}}else{let message=xhr.responseText;try{message=(JSON.parse(xhr.responseText) as {error?:string}).error||message}catch{}reject(new Error(`服务器返回 HTTP ${xhr.status}${message?`：${message.slice(0,160)}`:""}`))}};xhr.onerror=()=>{finish();reject(new Error("连接网站服务器失败，请稍后重试。"))};xhr.ontimeout=()=>{finish();reject(new Error("上传超过 30 分钟，已自动停止。"))};xhr.onabort=finish;xhr.send(file)})}

export default function AdminPanel(){const[token,setToken]=useState("");const[password,setPassword]=useState("");const[content,setContent]=useState<Partial<Content>>({});const[items,setItems]=useState<Item[]>([]);const[status,setStatus]=useState("");const[uploadProgress,setUploadProgress]=useState<UploadProgress|null>(null);const[uploading,setUploading]=useState(false);const headers=()=>({authorization:`Bearer ${token}`});
 const parsed=<T,>(key:keyof Content):T[]=>{try{const value=JSON.parse(String(content[key]||"[]"));return Array.isArray(value)?value:[]}catch{return[]}};const projects=parsed<ExtraProject>("additionalProjects"),experiences=parsed<ExtraExperience>("additionalExperiences");const setModules=(key:"additionalProjects"|"additionalExperiences",value:unknown[])=>setContent({...content,[key]:JSON.stringify(value)});const changeProject=(id:string,key:keyof ExtraProject,value:string)=>setModules("additionalProjects",projects.map(p=>p.id===id?{...p,[key]:value}:p));const changeExperience=(id:string,key:keyof ExtraExperience,value:string)=>setModules("additionalExperiences",experiences.map(x=>x.id===id?{...x,[key]:value}:x));
 async function load(authToken=token){if(!authToken)return;const r=await fetch("/api/admin",{headers:{authorization:`Bearer ${authToken}`}});if(r.ok){const d=await r.json();setContent(d.content);setItems(d.items)}else{sessionStorage.removeItem("portfolio-admin-token");setToken("");setStatus("登录已失效，请重新输入管理密码。")}}useEffect(()=>{const saved=sessionStorage.getItem("portfolio-admin-token")||"";if(saved){setToken(saved);load(saved)}},[]);
 async function login(e:React.FormEvent){e.preventDefault();setStatus("正在登录…");const r=await fetch("/api/admin/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password})});const d=await r.json();if(!r.ok){setStatus(d.error||"登录失败。");return}sessionStorage.setItem("portfolio-admin-token",d.token);setToken(d.token);setPassword("");setStatus("");await load(d.token)}function logout(){sessionStorage.removeItem("portfolio-admin-token");setToken("");setContent({});setItems([])}async function save(){setStatus("正在保存全部文字…");const r=await fetch("/api/admin",{method:"PUT",headers:{...headers(),"content-type":"application/json"},body:JSON.stringify(content)});const d=await r.json().catch(()=>({}));setStatus(r.ok?"全部文字已保存，公开网站已更新。":`保存失败：${d.error||r.status}`)}async function upload(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(uploading)return;const form=e.currentTarget;const fd=new FormData(form);const file=fd.get("file");if(!(file instanceof File)||!file.size){setStatus("请选择文件。");return}if(!/^(audio|video|image)\//.test(file.type)){setStatus("格式不支持：请选择音频、视频或图片文件。");return}if(file.size>500*1024*1024){setStatus(`文件为 ${(file.size/1024/1024).toFixed(1)}MB，单文件上限为 500MB。请压缩后重试。`);return}setUploading(true);setUploadProgress({percent:0,loaded:0,total:file.size,speed:0});try{setStatus(`正在通过国内服务器上传：${(file.size/1024/1024).toFixed(1)}MB…`);const uploadUrl=`/api/admin/media/upload?fileName=${encodeURIComponent(file.name)}&contentType=${encodeURIComponent(file.type)}&fileSize=${file.size}`;const uploaded=await uploadWithProgress(uploadUrl,file,token,setUploadProgress);setStatus("文件已上传，正在登记作品信息…");const r=await fetch("/api/admin/media",{method:"POST",headers:{...headers(),"content-type":"application/json"},body:JSON.stringify({path:uploaded.path,fileName:file.name,mediaType:file.type,title:fd.get("title"),category:fd.get("category"),description:fd.get("description"),placement:fd.get("placement")})});const result=await r.json();if(!r.ok)throw new Error(`作品登记失败：${result.error||r.status}`);form.reset();await load();setStatus("作品已上传并发布。")}catch(error){setStatus(`上传失败：${error instanceof Error?error.message:"未知错误"}`)}finally{setUploading(false)}}async function remove(id:number){if(!confirm("确定删除这件作品吗？"))return;const r=await fetch(`/api/admin/media?id=${id}`,{method:"DELETE",headers:headers()});if(r.ok){await load();setStatus("作品已删除。")}}
 const field=(key:keyof Content,label:string,multi=false)=><label key={key}>{label}{multi?<textarea value={content[key]??""} onChange={e=>setContent({...content,[key]:e.target.value})}/>:<input value={content[key]??""} onChange={e=>setContent({...content,[key]:e.target.value})}/>}</label>;
 if(!token)return <section className="admin-card admin-login"><h2>管理员登录</h2><p className="admin-note">输入网站管理密码。登录状态仅保留在当前浏览器标签页中。</p><form onSubmit={login}><label>管理密码<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password"/></label><button>登录后台</button></form>{status&&<p className="status">{status}</p>}</section>;
 return <><div className="admin-panel"><section className="admin-card full"><div className="admin-card-title"><div><h2>编辑网站全部文字</h2><p className="admin-note">标签列表使用英文逗号分隔；保存后公开网站立即更新。</p></div><button onClick={logout}>退出</button></div>{groups.map(([title,fields])=><div className="admin-field-group" key={title}><h3>{title}</h3><div className="admin-field-grid">{fields.map(([key,label,multi])=>field(key,label,Boolean(multi)))}</div></div>)}<button className="save-all" onClick={save}>保存全部文字和新增模块</button></section>
 <section className="admin-card full module-manager"><div className="module-head"><div><h2>新增项目模块</h2><p className="admin-note">新增后会自动出现在项目展示区，并加入媒体上传位置列表。</p></div><button onClick={()=>setModules("additionalProjects",[...projects,{id:crypto.randomUUID(),title:"新项目",kicker:"PROJECT",text:"项目介绍",tags:"Sound Design",meta:"YEAR · PLATFORM"}])}>＋ 新增项目</button></div>{projects.length===0?<p className="admin-note">暂无新增项目。</p>:projects.map((p,i)=><div className="module-row" key={p.id}><div className="module-row-head"><strong>项目 {i+1}</strong><button className="danger" onClick={()=>setModules("additionalProjects",projects.filter(x=>x.id!==p.id))}>删除模块</button></div><div className="admin-field-grid"><label>项目名称<input value={p.title} onChange={e=>changeProject(p.id,"title",e.target.value)}/></label><label>英文分类<input value={p.kicker} onChange={e=>changeProject(p.id,"kicker",e.target.value)}/></label><label>平台 / 年份<input value={p.meta} onChange={e=>changeProject(p.id,"meta",e.target.value)}/></label><label>标签（逗号分隔）<input value={p.tags} onChange={e=>changeProject(p.id,"tags",e.target.value)}/></label><label>项目介绍<textarea value={p.text} onChange={e=>changeProject(p.id,"text",e.target.value)}/></label></div></div>)}</section>
 <section className="admin-card full module-manager"><div className="module-head"><div><h2>新增实习 / 工作经历</h2><p className="admin-note">新增经历会自动接在现有经历之后并保持统一排版。</p></div><button onClick={()=>setModules("additionalExperiences",[...experiences,{id:crypto.randomUUID(),date:"20XX.XX — 20XX.XX",org:"单位名称",role:"职位",work:"参与项目或工作内容"}])}>＋ 新增经历</button></div>{experiences.length===0?<p className="admin-note">暂无新增经历。</p>:experiences.map((x,i)=><div className="module-row" key={x.id}><div className="module-row-head"><strong>经历 {i+1}</strong><button className="danger" onClick={()=>setModules("additionalExperiences",experiences.filter(e=>e.id!==x.id))}>删除模块</button></div><div className="admin-field-grid"><label>日期<input value={x.date} onChange={e=>changeExperience(x.id,"date",e.target.value)}/></label><label>单位<input value={x.org} onChange={e=>changeExperience(x.id,"org",e.target.value)}/></label><label>职位<input value={x.role} onChange={e=>changeExperience(x.id,"role",e.target.value)}/></label><label>项目 / 工作内容<textarea value={x.work} onChange={e=>changeExperience(x.id,"work",e.target.value)}/></label></div></div>)}</section>
 <section className="admin-card"><h2>上传或替换项目作品</h2><p className="admin-note">支持视频、音频和图片；单文件最高 500MB，视频建议使用 MP4（H.264）。</p><form onSubmit={upload}><label>展示位置<select name="placement" required disabled={uploading}><option value="reel">首页 Showreel</option><option value="spring">《春秋异闻录》项目卡</option><option value="xiaomi">小米汽车座舱演示卡</option><option value="tools">音频流程工具卡</option>{projects.map(p=><option key={p.id} value={`custom:${p.id}`}>{p.title}（新增项目）</option>)}<option value="archive">更多声音作品</option></select></label><label>作品名称<input name="title" required disabled={uploading}/></label><label>类别<select name="category" disabled={uploading}><option>游戏音频</option><option>声音设计</option><option>影视后期</option><option>空间音频</option><option>其他</option></select></label><label>简介<textarea name="description" disabled={uploading}/></label><label>文件（最高 500MB）<input name="file" type="file" accept="audio/*,video/*,image/*" required disabled={uploading}/></label><button disabled={uploading}>{uploading?"正在上传，请勿关闭页面":"上传并发布到对应位置"}</button>{uploadProgress&&<div className="upload-progress" role="status" aria-live="polite"><div className="upload-progress-head"><strong>{uploadProgress.percent}%</strong><span>{formatBytes(uploadProgress.loaded)} / {formatBytes(uploadProgress.total)}</span></div><progress max="100" value={uploadProgress.percent}/><small>{uploading?`当前平均速度 ${formatBytes(uploadProgress.speed)}/秒；连续 90 秒无进度会自动提示。`:uploadProgress.percent===100?"上传完成。":"本次上传已停止。"}</small></div>}</form></section><section className="admin-card"><h2>已发布作品</h2><div className="admin-items">{items.length===0?<p className="admin-note">还没有上传作品。</p>:items.map(i=><div className="admin-item" key={i.id}><div><strong>{i.title}</strong><br/><small>{placementNames[i.placement]||projects.find(p=>`custom:${p.id}`===i.placement)?.title||"更多声音作品"} · {i.category} · {i.fileName}</small></div><button className="danger" onClick={()=>remove(i.id)}>删除</button></div>)}</div></section></div>{status&&<p className="status" style={{maxWidth:1100,margin:"16px auto"}}>{status}</p>}</>}
