"use client";
import { createClient, type Session } from "@supabase/supabase-js";
import { useEffect,useMemo,useState } from "react";
type Item={id:number;title:string;category:string;description:string;fileName:string;mediaType:string};

export default function AdminPanel(){
 const supabase=useMemo(()=>createClient(process.env.NEXT_PUBLIC_SUPABASE_URL||"https://example.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||"placeholder"),[]);
 const [session,setSession]=useState<Session|null>(null);const [email,setEmail]=useState("");const [password,setPassword]=useState("");
 const [content,setContent]=useState({name:"",nameEn:"",headline:"",projectIntro:"",about:""});const [items,setItems]=useState<Item[]>([]);const [status,setStatus]=useState("");
 const headers=()=>({authorization:`Bearer ${session?.access_token||""}`});
 async function load(s=session){if(!s)return;const r=await fetch("/api/admin",{headers:{authorization:`Bearer ${s.access_token}`}});if(r.ok){const d=await r.json();setContent(d.content);setItems(d.items)}else setStatus("当前账号没有管理权限。")}
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);if(data.session)load(data.session)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 async function login(e:React.FormEvent){e.preventDefault();setStatus("正在登录…");const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)setStatus("登录失败，请检查邮箱和密码。");else{setSession(data.session);await load(data.session);setStatus("")}}
 async function save(){setStatus("正在保存…");const r=await fetch("/api/admin",{method:"PUT",headers:{...headers(),"content-type":"application/json"},body:JSON.stringify(content)});setStatus(r.ok?"文字已保存，公开网站已更新。":"保存失败。")}
 async function upload(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setStatus("正在上传…");const form=e.currentTarget;const r=await fetch("/api/admin/media",{method:"POST",headers:headers(),body:new FormData(form)});if(r.ok){form.reset();await load();setStatus("作品已上传并发布。")}else setStatus("上传失败，请检查文件格式或大小。")}
 async function remove(id:number){if(!confirm("确定删除这件作品吗？"))return;const r=await fetch(`/api/admin/media?id=${id}`,{method:"DELETE",headers:headers()});if(r.ok){await load();setStatus("作品已删除。")}}
 const field=(key:keyof typeof content,label:string,multi=false)=><label>{label}{multi?<textarea value={content[key]} onChange={e=>setContent({...content,[key]:e.target.value})}/>:<input value={content[key]} onChange={e=>setContent({...content,[key]:e.target.value})}/>}</label>;
 if(!session)return <section className="admin-card admin-login"><h2>管理员登录</h2><p className="admin-note">使用在 Supabase 中设置的管理员邮箱和密码。</p><form onSubmit={login}><label>邮箱<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>密码<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button type="submit">登录</button></form>{status&&<p className="status">{status}</p>}</section>;
 return <><div className="admin-panel"><section className="admin-card full"><div className="admin-card-title"><div><h2>编辑公开页文字</h2><p className="admin-note">管理账号：{session.user.email}</p></div><button onClick={()=>supabase.auth.signOut()}>退出</button></div>{field("name","中文姓名")}{field("nameEn","英文姓名")}{field("headline","首页个人定位",true)}{field("projectIntro","《春秋异闻录》项目介绍",true)}{field("about","关于我",true)}<button onClick={save}>保存文字</button></section><section className="admin-card"><h2>上传新作品</h2><p className="admin-note">支持音频、视频和图片，上传后自动显示在公开页面。</p><form onSubmit={upload}><label>作品名称<input name="title" required/></label><label>类别<select name="category"><option>游戏音频</option><option>声音设计</option><option>影视后期</option><option>空间音频</option><option>其他</option></select></label><label>简介<textarea name="description"/></label><label>文件<input name="file" type="file" accept="audio/*,video/*,image/*" required/></label><button type="submit">上传并发布</button></form></section><section className="admin-card"><h2>已发布作品</h2><div className="admin-items">{items.length===0?<p className="admin-note">还没有上传作品。</p>:items.map(i=><div className="admin-item" key={i.id}><div><strong>{i.title}</strong><br/><small>{i.category} · {i.fileName}</small></div><button className="danger" onClick={()=>remove(i.id)}>删除</button></div>)}</div></section></div>{status&&<p className="status" style={{maxWidth:1100,margin:"16px auto"}}>{status}</p>}</>;
}
