"use client";
import {createClient,type Session} from "@supabase/supabase-js";import {useEffect,useMemo,useState} from "react";import type {Content} from "../../lib/data";
type Item={id:number;title:string;category:string;description:string;fileName:string;mediaType:string};
const groups=[
 ["基本信息",[["name","中文姓名"],["nameEn","英文姓名"],["role","职业定位"],["availability","可工作状态"],["email","联系邮箱"],["phone","联系电话"],["portfolioLabel","作品集链接文字"],["portfolioUrl","作品集网址"],["footerText","页脚职业文字"]]],
 ["导航",[["navWork","作品"],["navReel","Showreel"],["navAbout","关于"],["navContact","联系"]]],
 ["首页首屏",[["heroTitleBefore","主标题第一行"],["heroTitleAccent","主标题强调文字"],["heroTitleAfter","主标题结尾"],["headline","个人定位简介",true],["heroPrimary","主按钮"],["heroSecondary","Showreel 按钮"],["reelTitle","Showreel 标题"],["reelEmpty","未上传视频提示"],["reelLabel","Showreel 标签"]]],
 ["作品区",[["workKicker","英文小标题"],["workTitle","中文标题"],["workIntro","区域简介",true],["projectMeta","项目元信息"],["projectName","项目名称"],["projectRole","项目职责"],["projectIntro","项目简介",true],["projectFact1Label","数据 1 名称"],["projectFact1Value","数据 1 内容"],["projectFact2Label","数据 2 名称"],["projectFact2Value","数据 2 内容"],["projectFact3Label","数据 3 名称"],["projectFact3Value","数据 3 内容"],["projectBullets","项目工作内容（每行一项）",true],["projectTags","项目标签（逗号分隔）"]]],
 ["其他作品",[["spatialKicker","空间音频英文标题"],["spatialTitle","空间音频项目名"],["spatialText","空间音频介绍",true],["spatialTags","空间音频标签"],["toolsKicker","工具英文标题"],["toolsTitle","工具项目名"],["toolsText","工具介绍",true],["toolsTags","工具标签"],["toolsVisual","工具卡片大字"],["toolsCredit","工具卡片署名"],["mediaKicker","作品库英文标题"],["mediaTitle","作品库中文标题"]]],
 ["工作经历",[["experienceKicker","英文标题"],["experienceTitle","中文标题"],["exp1Date","经历 1 日期"],["exp1Org","经历 1 单位"],["exp1Role","经历 1 职位"],["exp1Work","经历 1 项目"],["exp2Date","经历 2 日期"],["exp2Org","经历 2 单位"],["exp2Role","经历 2 职位"],["exp2Work","经历 2 项目"],["exp3Date","经历 3 日期"],["exp3Org","经历 3 单位"],["exp3Role","经历 3 职位"],["exp3Work","经历 3 项目"]]],
 ["关于与教育",[["aboutKicker","英文标题"],["aboutTitle","中文标题"],["about","个人介绍",true],["location","所在地"],["edu1Date","教育 1 日期"],["edu1School","教育 1 学校"],["edu1Text","教育 1 专业"],["edu2Date","教育 2 日期"],["edu2School","教育 2 学校"],["edu2Text","教育 2 专业"],["skills","技能（逗号分隔）",true]]],
 ["联系区",[["contactKicker","英文标题"],["contactTitleBefore","标题第一行"],["contactTitleAccent","强调文字"],["contactTitleAfter","标题结尾"],["contactIntro","联系说明",true]]],
] as const;

export default function AdminPanel(){const supabase=useMemo(()=>createClient(process.env.NEXT_PUBLIC_SUPABASE_URL||"https://example.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||"placeholder"),[]);const[session,setSession]=useState<Session|null>(null);const[email,setEmail]=useState("");const[content,setContent]=useState<Partial<Content>>({});const[items,setItems]=useState<Item[]>([]);const[status,setStatus]=useState("");const headers=()=>({authorization:`Bearer ${session?.access_token||""}`});
 async function load(s=session){if(!s)return;const r=await fetch("/api/admin",{headers:{authorization:`Bearer ${s.access_token}`}});if(r.ok){const d=await r.json();setContent(d.content);setItems(d.items)}else setStatus("当前账号没有管理权限。")}useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);if(data.session)load(data.session)});const{data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 async function login(e:React.FormEvent){e.preventDefault();setStatus("正在发送登录链接…");const{error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:`${location.origin}/admin`}});setStatus(error?"发送失败，请确认邮箱地址。":"登录链接已发送，请前往邮箱点击确认。")}async function save(){setStatus("正在保存全部文字…");const r=await fetch("/api/admin",{method:"PUT",headers:{...headers(),"content-type":"application/json"},body:JSON.stringify(content)});setStatus(r.ok?"全部文字已保存，公开网站已更新。":"保存失败。")}async function upload(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setStatus("正在上传…");const form=e.currentTarget;const r=await fetch("/api/admin/media",{method:"POST",headers:headers(),body:new FormData(form)});if(r.ok){form.reset();await load();setStatus("作品已上传并发布。")}else setStatus("上传失败，请检查文件格式或大小。")}async function remove(id:number){if(!confirm("确定删除这件作品吗？"))return;const r=await fetch(`/api/admin/media?id=${id}`,{method:"DELETE",headers:headers()});if(r.ok){await load();setStatus("作品已删除。")}}
 const field=(key:keyof Content,label:string,multi=false)=><label key={key}>{label}{multi?<textarea value={content[key]??""} onChange={e=>setContent({...content,[key]:e.target.value})}/>:<input value={content[key]??""} onChange={e=>setContent({...content,[key]:e.target.value})}/>}</label>;
 if(!session)return <section className="admin-card admin-login"><h2>管理员登录</h2><p className="admin-note">输入管理员邮箱，我们会发送一次性安全登录链接。</p><form onSubmit={login}><label>管理员邮箱<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><button>发送登录链接</button></form>{status&&<p className="status">{status}</p>}</section>;
 return <><div className="admin-panel"><section className="admin-card full"><div className="admin-card-title"><div><h2>编辑网站全部文字</h2><p className="admin-note">管理账号：{session.user.email}。标签列表使用英文逗号分隔。</p></div><button onClick={()=>supabase.auth.signOut()}>退出</button></div>{groups.map(([title,fields])=><div className="admin-field-group" key={title}><h3>{title}</h3><div className="admin-field-grid">{fields.map(([key,label,multi])=>field(key,label,Boolean(multi)))}</div></div>)}<button className="save-all" onClick={save}>保存全部文字</button></section><section className="admin-card"><h2>上传新作品</h2><p className="admin-note">支持音频、视频和图片，上传后自动显示。</p><form onSubmit={upload}><label>作品名称<input name="title" required/></label><label>类别<select name="category"><option>游戏音频</option><option>声音设计</option><option>影视后期</option><option>空间音频</option><option>其他</option></select></label><label>简介<textarea name="description"/></label><label>文件<input name="file" type="file" accept="audio/*,video/*,image/*" required/></label><button>上传并发布</button></form></section><section className="admin-card"><h2>已发布作品</h2><div className="admin-items">{items.length===0?<p className="admin-note">还没有上传作品。</p>:items.map(i=><div className="admin-item" key={i.id}><div><strong>{i.title}</strong><br/><small>{i.category} · {i.fileName}</small></div><button className="danger" onClick={()=>remove(i.id)}>删除</button></div>)}</div></section></div>{status&&<p className="status" style={{maxWidth:1100,margin:"16px auto"}}>{status}</p>}</>}
