import {getPublicData,type PortfolioItem} from "../lib/data";
export const dynamic="force-dynamic";
const split=(s:string)=>s.split(/\s*,\s*/).filter(Boolean);
function Media({item,className=""}:{item?:PortfolioItem;className?:string}){if(!item)return null;if(item.mediaType.startsWith("video"))return <video className={className} controls preload="metadata" src={`/api/media/${item.id}`}/>;if(item.mediaType.startsWith("audio"))return <div className={`project-audio ${className}`}><strong>{item.title}</strong><audio controls preload="metadata" src={`/api/media/${item.id}`}/></div>;return <img className={className} src={`/api/media/${item.id}`} alt={item.title}/>}

export default async function Home(){const d=await getPublicData();const placed=(key:string)=>d.items.find(i=>i.placement===key);const reel=placed("reel"),spring=placed("spring"),xiaomi=placed("xiaomi"),toolsMedia=placed("tools");const archive=d.items.filter(i=>!i.placement||i.placement==="archive");const experiences=[1,2,3].map(n=>({date:d[`exp${n}Date` as keyof typeof d] as string,org:d[`exp${n}Org` as keyof typeof d] as string,role:d[`exp${n}Role` as keyof typeof d] as string,work:d[`exp${n}Work` as keyof typeof d] as string}));const placeholder=(title:string,sub="在后台上传视频 / 音频 / 图片")=><div className="media-placeholder"><span>PROJECT MEDIA</span><strong>{title}</strong><small>{sub}</small></div>;return <main id="top">
 <nav className="nav shell"><a className="brand" href="#top"><span>YL</span>{d.nameEn}</a><div className="navlinks"><a href="#work">{d.navWork}</a><a href="#reel">{d.navReel}</a><a href="#about">{d.navAbout}</a><a href="#contact">{d.navContact}</a></div><a className="nav-mail" href={`mailto:${d.email}`}>{d.availability}</a></nav>
 <header className="hero shell"><div className="hero-copy"><p className="eyebrow">{d.role}</p><h1>{d.heroTitleBefore}<br/><em>{d.heroTitleAccent}</em>{d.heroTitleAfter}</h1><p className="lead">{d.headline}</p><div className="hero-actions"><a className="button primary" href="#work">{d.heroPrimary}</a><a className="text-link" href="#reel">{d.heroSecondary} <span>↓</span></a></div></div><div id="reel" className="reel-panel">{reel?<Media item={reel}/>:<div className="reel-empty"><div className="play-mark">▶</div><div><strong>{d.reelTitle}</strong><span>{d.reelEmpty}</span></div></div>}<div className="reel-meta"><span>01</span><span>{reel?reel.title:d.reelLabel}</span></div></div></header>
 <section id="work" className="section shell"><div className="section-title"><p className="eyebrow">{d.workKicker}</p><h2>{d.workTitle}</h2><p>{d.workIntro}</p></div>
 <article className="case case-main"><div className="case-cover spring-cover">{spring?<Media item={spring} className="slot-media"/>:placeholder(d.projectName)}<div className="cover-badge">{d.projectMeta}</div></div><div className="case-info"><div className="case-index">01</div><p className="eyebrow">{d.projectRole}</p><h3>{d.projectName}</h3><p className="case-lead">{d.projectIntro}</p><div className="case-facts"><div><span>{d.projectFact1Label}</span><strong>{d.projectFact1Value}</strong></div><div><span>{d.projectFact2Label}</span><strong>{d.projectFact2Value}</strong></div><div><span>{d.projectFact3Label}</span><strong>{d.projectFact3Value}</strong></div></div><ul>{d.projectBullets.split("\n").filter(Boolean).map(x=><li key={x}>{x}</li>)}</ul><div className="tags">{split(d.projectTags).map(x=><span key={x}>{x}</span>)}</div></div></article>
 <div className="case-grid"><article className="mini-case"><div className="mini-visual">{xiaomi?<Media item={xiaomi} className="slot-media"/>:placeholder(d.spatialTitle)}</div><div className="mini-copy"><p className="eyebrow">{d.spatialKicker}</p><h3>{d.spatialTitle}</h3><p>{d.spatialText}</p><div className="tags">{split(d.spatialTags).map(x=><span key={x}>{x}</span>)}</div></div></article><article className="mini-case"><div className="mini-visual">{toolsMedia?<Media item={toolsMedia} className="slot-media"/>:placeholder(d.toolsVisual,d.toolsCredit)}<span className="mini-badge">{d.toolsVisual} · {d.toolsCredit}</span></div><div className="mini-copy"><p className="eyebrow">{d.toolsKicker}</p><h3>{d.toolsTitle}</h3><p>{d.toolsText}</p><div className="tags">{split(d.toolsTags).map(x=><span key={x}>{x}</span>)}</div></div></article></div>
 {archive.length>0&&<div className="uploads"><div className="subhead"><p className="eyebrow">{d.mediaKicker}</p><h2>{d.mediaTitle}</h2></div><div className="media-grid">{archive.map(i=><article className="media-card" key={i.id}><Media item={i}/><div><span>{i.category}</span><h3>{i.title}</h3><p>{i.description}</p></div></article>)}</div></div>}</section>
 <section className="credits-section"><div className="shell"><div className="section-title inverted"><p className="eyebrow">{d.experienceKicker}</p><h2>{d.experienceTitle}</h2></div><div className="credits">{experiences.map((e,i)=><article key={i}><span className="credit-no">0{i+1}</span><span className="credit-date">{e.date}</span><div><h3>{e.org}</h3><p>{e.role}</p></div><p className="credit-work">{e.work}</p></article>)}</div></div></section>
 <section id="about" className="section shell about about-no-photo"><div className="about-copy"><p className="eyebrow">{d.aboutKicker}</p><h2>{d.aboutTitle}</h2><p className="identity-line">{d.name} · {d.nameEn}</p><p className="about-intro">{d.about}</p><p className="location-line">{d.location}</p><div className="education"><div><span>{d.edu1Date}</span><strong>{d.edu1School}</strong><p>{d.edu1Text}</p></div><div><span>{d.edu2Date}</span><strong>{d.edu2School}</strong><p>{d.edu2Text}</p></div></div><div className="tool-line">{split(d.skills).map(x=><span key={x}>{x}</span>)}</div></div></section>
 <footer id="contact" className="footer"><div className="shell footer-grid"><div><p className="eyebrow">{d.contactKicker}</p><h2>{d.contactTitleBefore}<br/><em>{d.contactTitleAccent}</em>{d.contactTitleAfter}</h2></div><div className="contact-list"><p>{d.contactIntro}</p><a href={`mailto:${d.email}`}>{d.email} ↗</a><a href={`tel:${d.phone.replace(/\s/g,"")}`}>{d.phone}</a><a href={d.portfolioUrl} target="_blank" rel="noreferrer">{d.portfolioLabel}</a></div></div><div className="shell footer-bottom"><span>© 2026 {d.nameEn}</span><span>{d.footerText}</span><a href="/admin">网站管理</a></div></footer>
 </main>}
